### ISSUE TITLE
Error on Plugin Activation

### ISSUE THREAD

**Issue by clas-web** [clas-web/woocommerce-customization#1]
When the plugin is initially activated, you get the following error:
Fatal error: Cannot redeclare woocommerce_output_related_products() (previously declared in /home/pages/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php:1058) in /home/pages/public_html/wp-content/plugins/custom_woocommerce/custom_woocommerce.php on line 24

This can be resolved as follows:
1. commenting out line 24
2. activate plugin
3. uncomment line 24

**Comment by akforsyt** [comment]
fixed by 20091ba7d91f011ef359a38237bb7f794fecbf91
