### ISSUE TITLE
Request button for items with multiple models not working in some browsers

### ISSUE THREAD

**Issue by clas-web** [clas-web/woocommerce-customization#5]
The request button for items with multiple models not working in Chrome, see:
https://clas-pages.uncc.edu/clas-equipment/product/ipad-16gb/

This is because of the issue described here:
https://support.woothemes.com/hc/en-us/articles/203104197-Variable-Product-Add-to-Cart-Not-Working
Is this something that can be fixed?
 
If not, then I believe I can resolve it by doing what is described here:
http://docs.woothemes.com/document/jquery-cookie-fails-to-load/

**Comment by clas-web** [comment]
Issue may be caused by a particular version of MOD_SECURITY core ruleset. See:
http://docs.woothemes.com/document/jquery-cookie-fails-to-load/

**Comment by marpa** [comment]
MOD_SECURITY core ruleset was updated in PROD and did NOT resolve the problem

**Comment by marpa** [comment]
It could be that this plugin could be modified to fix this problem, see:
http://docs.woothemes.com/document/jquery-cookie-fails-to-load/

**Comment by akforsyt** [comment]
Fixed by updating this plugin to include custom jquery_cookie files.
See commits e1ab51a80f30477a7629e4064d25703de1a3efd6 and b9278bc6c84e6fca80c9230e1f0a2798256635c4
