### ISSUE TITLE
Completed Orders redirect to a blank screen

### ISSUE THREAD

**Issue by marpa** [clas-web/woocommerce-customization#6]
When the status of an order is change to "completed" and the order is updated (i.e. the update button is clicked), the browser is redirected to a blank page.

**Comment by marpa** [comment]
It looks like the form variables are being dropped when the status is completed.  Specifically the post id and the action (e.g. post=<<id>>&action=edit

Works fine for other order statues...

**Comment by akforsyt** [comment]
fixed by 2dc6d34d63f021dedd45416a40782371a413ee8f
