### ISSUE TITLE
Cannot Send Request due to address error

### ISSUE THREAD

**Issue by marpa** [clas-web/woocommerce-customization#7]
When attempted to send a request, the send-request page displays the following error:

> Please enter an address to continue.

This error is displayed even when the address is included.  Forum posts suggest is can result when forms are customized to not include shipping country, see:
[https://wordpress.org/support/topic/please-enter-an-address-to-continue/](https://wordpress.org/support/topic/please-enter-an-address-to-continue/)

This plugin does remove the shipping country field... Ideally we could simply set this field = US without having to display to end user...

**Comment by akforsyt** [comment]
fixed by 20091ba7d91f011ef359a38237bb7f794fecbf91
